import type { Alert } from '@/types/sensors'

interface NodeStatus {
  id: string
  location: string
  health: number
  threatLevel: string
  sensors: number
  sensorsOnline: number
  alerts: number
  uptime_h: number
  status: string
}

export function exportAlertsCsv(alerts: Alert[]): void {
  const headers = ['alert_id', 'timestamp', 'classification', 'threat_level', 'sensor_family', 'location', 'source_sensors', 'acknowledged', 'annotation']
  const rows = alerts.map((a) => [
    a.id,
    a.timestamp,
    a.classification,
    a.threat_level,
    a.sensor_family ?? '',
    a.location,
    a.source_sensors.join(';'),
    a.acknowledged ? 'YES' : 'NO',
    a.annotation ?? '',
  ])

  const csv = [headers, ...rows]
    .map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(','))
    .join('\n')

  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `sis-alerts-${new Date().toISOString().slice(0, 10)}.csv`
  link.click()
  URL.revokeObjectURL(url)
}

export function printIncidentReport(opts: {
  nodes: NodeStatus[]
  totalAlerts: number
  narrative: string
  operator: string
}): void {
  const { nodes, totalAlerts, narrative, operator } = opts
  const now = new Date()
  const onlineNodes = nodes.filter((n) => n.status === 'ONLINE').length
  const offlineNodes = nodes.filter((n) => n.status === 'OFFLINE').length
  const topThreat = nodes.reduce<string>((max, n) => {
    const order: Record<string, number> = { CRITICAL: 5, HIGH: 4, MEDIUM: 3, LOW: 2, CLEAR: 1 }
    return (order[n.threatLevel] ?? 0) > (order[max] ?? 0) ? n.threatLevel : max
  }, 'CLEAR')

  const nodeRows = nodes
    .map(
      (n) =>
        `<tr><td>${n.id}</td><td>${n.location}</td><td>${n.status}</td><td>${n.threatLevel}</td>` +
        `<td>${n.sensorsOnline}/${n.sensors}</td><td>${n.alerts}</td><td>${n.health.toFixed(0)}%</td></tr>`
    )
    .join('')

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>SIS Incident Report – ${now.toLocaleString()}</title>
<style>
  body { font-family: Arial, sans-serif; font-size: 11px; color: #000; margin: 24px; }
  h1 { font-size: 16px; margin: 0 0 4px; }
  .subtitle { color: #555; font-size: 10px; margin-bottom: 16px; }
  .meta { border: 1px solid #ccc; padding: 8px 12px; margin-bottom: 16px; line-height: 1.7; }
  .meta strong { display: inline-block; width: 140px; }
  table { border-collapse: collapse; width: 100%; margin-bottom: 16px; }
  th, td { border: 1px solid #ccc; padding: 5px 8px; text-align: left; font-size: 10px; }
  th { background: #e8e8e8; font-weight: bold; }
  .narrative { border: 1px solid #ccc; padding: 10px 12px; min-height: 80px; line-height: 1.6; }
  .footer { margin-top: 24px; font-size: 9px; color: #888; border-top: 1px solid #ccc; padding-top: 8px; }
  @media print { body { margin: 10mm; } }
</style>
</head>
<body>
<h1>IINVSYS SIS — Incident Report</h1>
<div class="subtitle">BHQN / CLASSIFICATION: RESTRICTED</div>

<div class="meta">
  <div><strong>Date / Time:</strong> ${now.toLocaleString()} (${now.toUTCString()})</div>
  <div><strong>Operator:</strong> ${operator || '—'}</div>
  <div><strong>Active Alerts:</strong> ${totalAlerts}</div>
  <div><strong>Nodes Online:</strong> ${onlineNodes}/${nodes.length} (${offlineNodes} OFFLINE)</div>
  <div><strong>Highest Threat:</strong> ${topThreat}</div>
</div>

<h2 style="font-size:12px;margin:0 0 6px;">Node Status</h2>
<table>
  <thead>
    <tr><th>Node ID</th><th>Location</th><th>Status</th><th>Threat</th><th>Sensors</th><th>Alerts</th><th>Health</th></tr>
  </thead>
  <tbody>${nodeRows}</tbody>
</table>

<h2 style="font-size:12px;margin:0 0 6px;">Narrative</h2>
<div class="narrative">${narrative || '<em>No narrative provided.</em>'}</div>

<div class="footer">
  Generated by SIS Dashboard v1.0.0 — IINVSYS Pvt Ltd &nbsp;|&nbsp;
  Ref: SIS-RPT-${Date.now().toString(36).toUpperCase()}
</div>
</body>
</html>`

  const win = window.open('', '_blank', 'width=800,height=600')
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.focus()
  setTimeout(() => { win.print(); win.close() }, 500)
}

export function printHandoverReport(opts: {
  nodes: NodeStatus[]
  totalAlerts: number
  notes: string
  period: string
  operator: string
}): void {
  const { nodes, totalAlerts, notes, period, operator } = opts
  const now = new Date()
  const onlineNodes = nodes.filter((n) => n.status === 'ONLINE').length

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>SIS Shift Handover – ${now.toLocaleString()}</title>
<style>
  body { font-family: Arial, sans-serif; font-size: 11px; color: #000; margin: 24px; }
  h1 { font-size: 16px; margin: 0 0 4px; }
  .subtitle { color: #555; font-size: 10px; margin-bottom: 16px; }
  .meta { border: 1px solid #ccc; padding: 8px 12px; margin-bottom: 16px; line-height: 1.7; }
  .meta strong { display: inline-block; width: 140px; }
  .notes { border: 1px solid #ccc; padding: 10px 12px; min-height: 100px; line-height: 1.6; white-space: pre-wrap; }
  .sig-line { margin-top: 32px; display: flex; gap: 60px; }
  .sig-box { border-top: 1px solid #000; padding-top: 4px; width: 200px; font-size: 10px; color: #555; }
  .footer { margin-top: 24px; font-size: 9px; color: #888; border-top: 1px solid #ccc; padding-top: 8px; }
  @media print { body { margin: 10mm; } }
</style>
</head>
<body>
<h1>IINVSYS SIS — Shift Handover Summary</h1>
<div class="subtitle">Period: Last ${period} &nbsp;|&nbsp; CLASSIFICATION: RESTRICTED</div>

<div class="meta">
  <div><strong>Handover Time:</strong> ${now.toLocaleString()}</div>
  <div><strong>Outgoing Operator:</strong> ${operator || '—'}</div>
  <div><strong>Nodes Online:</strong> ${onlineNodes}/${nodes.length}</div>
  <div><strong>Total Active Alerts:</strong> ${totalAlerts}</div>
</div>

<h2 style="font-size:12px;margin:0 0 6px;">Handover Notes</h2>
<div class="notes">${notes || 'No notes provided.'}</div>

<div class="sig-line">
  <div class="sig-box">Outgoing Operator Signature</div>
  <div class="sig-box">Incoming Operator Signature</div>
  <div class="sig-box">Supervisor / Witness</div>
</div>

<div class="footer">
  Generated by SIS Dashboard v1.0.0 — IINVSYS Pvt Ltd &nbsp;|&nbsp;
  Ref: SIS-HVR-${Date.now().toString(36).toUpperCase()}
</div>
</body>
</html>`

  const win = window.open('', '_blank', 'width=800,height=600')
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.focus()
  setTimeout(() => { win.print(); win.close() }, 500)
}
